In [ ]:
# Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose 
# you have collected data on the amount of time students spend studying for an exam and their final exam 
# scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

# Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables. 
# Suppose you have collected data on the amount of sleep individuals get each night and their overall job 
# satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two 
# variables and interpret the result.

# Q3. Suppose you are conducting a study to examine the relationship between the number of hours of 
# exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables 
# for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation 
# between these two variables and compare the results.

# Q4. A researcher is interested in examining the relationship between the number of hours individuals 
# spend watching television per day and their level of physical activity. The researcher collected data on 
# both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between 
# these two variables.

# Q5. A survey was conducted to examine the relationship between age and preference for a particular 
# brand of soft drink. The survey results are shown below:
    
#     Age(Years)                     Soft drink preference
#        25                                 coke
#        42                                 pepsi
#        37                            mountain dew
#        19                                 coke
#        31                                 pepsi
#        28                                 coke
      
# Q6. A company is interested in examining the relationship between the number of sales calls made per day 
# and the number of sales made per week. The company collected data on both variables from a sample of 
# 30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [ ]:
# Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose 
# you have collected data on the amount of time students spend studying for an exam and their final exam 
# scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [1]:
# To calculate the Pearson correlation coefficient between the time students spend studying and their final exam scores, you need to follow these steps:

# Calculate the mean and standard deviation for each variable.
# Calculate the covariance between the two variables.
# Divide the covariance by the product of the standard deviations of the two variables.
# Interpret the result.
# Let's assume you have the following data:

# Time spent studying (in hours): 5, 10, 15, 20, 25
# Final exam scores: 60, 70, 80, 90, 100

# Step 1: Calculate the mean and standard deviation for each variable.

# Mean of time spent studying = (5+10+15+20+25)/5 = 15
# Standard deviation of time spent studying = 7.91

# Mean of final exam scores = (60+70+80+90+100)/5 = 80
# Standard deviation of final exam scores = 15.81

# Step 2: Calculate the covariance between the two variables.

# Covariance = Σ[(x - mean of x)(y - mean of y)]/(n-1)
# Where x is the time spent studying, y is the final exam score, and n is the sample size.

# Covariance = [(5-15)(60-80) + (10-15)(70-80) + (15-15)(80-80) + (20-15)(90-80) + (25-15)*(100-80)]/(5-1)
# Covariance = 250

# Step 3: Divide the covariance by the product of the standard deviations of the two variables.

# Pearson correlation coefficient (r) = Covariance / (Standard deviation of time spent studying * Standard deviation of final exam scores)
# r = 78.125 / (7.91 * 15.81)
# r = 0.95

# Step 4: Interpret the result.

# The Pearson correlation coefficient (r) is 0.95, which indicates a strong positive linear relationship between the time students spend studying 
# and their final exam scores. In other words, the more time students spend studying, the higher their final exam scores tend to be. 
# However, it's important to note that correlation does not imply causation, so we cannot conclude that studying causes higher exam scores 
# without further investigation.

In [4]:
# Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables. 
# Suppose you have collected data on the amount of sleep individuals get each night and their overall job 
# satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two 
# variables and interpret the result.

In [6]:
from scipy.stats import spearmanr

# Amount of sleep individuals get each night (in hours)
x = [8, 7, 6, 7, 5, 9, 6, 8, 7, 8]

# Overall job satisfaction level on a scale of 1 to 10
y = [9, 7, 6, 8, 5, 10, 7, 9, 8, 9]

# Calculate the Spearman's rank correlation coefficient
cho, p_val = spearmanr(x, y)

print("Spearman's rank correlation coefficient:", cho)
print("p-value:", p_val)


Spearman's rank correlation coefficient: 0.9746473773006418
p-value: 1.753053927876978e-06


In [7]:
# The output shows that the Spearman's rank correlation coefficient between the amount of sleep individuals get each night and their overall job satisfaction
# level is 0.97, which indicates a strong positive monotonic relationship between the two variables. 
# This means that as the amount of sleep individuals get each night increases, their overall job satisfaction level tends to increase as well.

# The p-value is less than 0.05, indicating that the correlation is statistically significant at a 95% confidence level. 
# This means that we can reject the null hypothesis that there is no correlation between the two variables,
# and conclude that there is a significant positive monotonic relationship between the amount of sleep individuals get each night
# and their overall job satisfaction level.

In [8]:
# Q3. Suppose you are conducting a study to examine the relationship between the number of hours of 
# exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables 
# for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation 
# between these two variables and compare the results.

In [11]:
import numpy as np
from scipy.stats import pearsonr, spearmanr

# Number of hours of exercise per week
x = np.array([3, 5, 2, 6, 4, 5, 1, 2, 3, 5, 2, 6, 4, 5, 1, 2, 3, 5, 2, 6, 4, 5, 1, 2, 3, 5, 2, 6, 4, 5, 1, 2, 3, 5, 2, 6, 4, 5, 1, 2, 3, 5, 2, 6, 4, 5, 1, 2, 3, 5])

# Body mass index (BMI)
y = np.array([25.2, 26.4, 23.1, 28.8, 25.9, 27.3, 22.2, 23.9, 24.6, 26.8, 23.4, 28.1, 25.6, 27.2, 22.7, 24.0, 24.9, 
              26.5, 23.2, 28.7, 25.3, 27.5, 22.8, 24.3, 24.8, 26.6, 23.3, 28.4, 25.0, 27.6, 22.9, 24.4, 24.7, 26.7, 
              23.0, 28.3, 25.1, 27.7, 22.6, 24.1, 24.5, 26.9, 23.5, 28.2, 25.4, 27.8, 22.3, 24.2, 24.9, 26.3])

# Calculate the Pearson correlation coefficient
r, pval = pearsonr(x, y)

print("Pearson correlation coefficient:", r)
print("p-value:", pval)

# Calculate the Spearman's rank correlation coefficient
rho, pval = spearmanr(x, y)

print("Spearman's rank correlation coefficient:", rho)
print("p-value:", pval)


Pearson correlation coefficient: 0.972683192158011
p-value: 4.229488697573135e-32
Spearman's rank correlation coefficient: 0.9790848161603345
p-value: 7.483233307023227e-35


In [12]:
# The output shows that both the Pearson correlation coefficient and the Spearman's rank correlation coefficient are positive, 
# indicating a strong positive relationship between the number of hours of exercise per week and body mass index.

In [13]:
# Q4. A researcher is interested in examining the relationship between the number of hours individuals 
# spend watching television per day and their level of physical activity. The researcher collected data on 
# both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between 
# these two variables.

In [17]:
from scipy.stats import pearsonr

# create two lists of data
hours_tv = [2, 3, 1, 4, 5, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 1, 4, 5, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 1, 4, 5, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 3]
activity = [30, 60, 45, 15, 10, 20, 30, 15, 45, 50, 40, 20, 10, 60, 45, 30, 20, 10, 40, 50, 30, 15, 10, 20, 30, 15, 45, 50, 40, 20, 10, 60, 45, 30, 20, 10, 40, 50, 30, 15, 10, 20, 30, 15, 45, 50, 40, 20, 10, 60, 45, 30, 20]

# calculate Pearson correlation coefficient and p-value
corr_coef, p_value = pearsonr(hours_tv, activity)

print("Pearson correlation coefficient: {:.2f}".format(corr_coef))
print("p-value: {:.2f}".format(p_value))

ValueError: x and y must have the same length.

In [23]:
# Q5. A survey was conducted to examine the relationship between age and preference for a particular 
# brand of soft drink. The survey results are shown below:
    
#     Age(Years)                     Soft drink preference

#        25                                 coke
#        42                                 pepsi
#        37                            mountain dew
#        19                                 coke
#        31                                 pepsi
#        28                                 coke

In [25]:
import pandas as pd
from scipy.stats import chi2_contingency

# create a dictionary of the data
data = {
    "Age": [25, 42, 37, 19, 31, 28],
    "Soft drink preference": ["coke", "pepsi", "mountain dew", "coke", "pepsi", "coke"]
}

# create a pandas dataframe
df = pd.DataFrame(data)

# create a contingency table
contingency_table = pd.crosstab(df["Age"], df["Soft drink preference"])

# perform chi-square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)

# print results
print(contingency_table)
print("Chi-square test statistic: {:.2f}".format(chi2))
print("p-value: {:.4f}".format(p))
print("degrees of freedom: {}".format(dof))
print("expected frequencies:\n{}".format(expected))


Soft drink preference  coke  mountain dew  pepsi
Age                                             
19                        1             0      0
25                        1             0      0
28                        1             0      0
31                        0             0      1
37                        0             1      0
42                        0             0      1
Chi-square test statistic: 12.00
p-value: 0.2851
degrees of freedom: 10
expected frequencies:
[[0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]
 [0.5        0.16666667 0.33333333]]


In [26]:
#Since the p-value is greater than 0.05, we fail to reject the null hypothesis that there is no significant association between age and soft drink preference.

In [27]:
# Q6. A company is interested in examining the relationship between the number of sales calls made per day 
# and the number of sales made per week. The company collected data on both variables from a sample of 
# 30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [28]:
# Assuming the data for the number of sales calls made per day and the number of sales made per week are already collected and stored in two separate lists,
# let's call them "calls" and "sales" respectively.

# Here's how you can calculate the Pearson correlation coefficient in Python using the pearsonr function from the scipy.stats module:

In [31]:
from scipy.stats import pearsonr

# data
calls = [20, 15, 18, 22, 25, 17, 16, 21, 19, 24, 23, 16, 18, 20, 19, 22, 17, 15, 21, 23, 16, 19, 20, 18, 24, 21, 25, 17, 22, 15]
sales = [3, 2, 2, 4, 5, 3, 2, 4, 3, 5, 4, 2, 2, 3, 3, 4, 2, 2, 4, 4, 2, 3, 3, 2, 5, 4, 5, 3, 4, 2]

# calculate Pearson correlation coefficient and p-value
corr_coef, p_value = pearsonr(calls, sales)

print("Pearson correlation coefficient: {:.2f}".format(corr_coef)) ##{:.2f} is a string formatting syntax in Python. It is used to format a floating-point number with two decimal places.
print("p-value: {:.2f}".format(p_value))


Pearson correlation coefficient: 0.94
p-value: 0.00


In [32]:
# The Pearson correlation coefficient is 0.94, which indicates a strong positive correlation between the number of sales calls made per day 
# and the number of sales made per week. The p-value is less than 0.05, which indicates that the correlation is statistically significant.